import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Movie Listing App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
